/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5997a2c4-b75e-4c2c-a046-dff7f53228aa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EeLqYSqck",
    "aws_user_pools_web_client_id": "6tc47khec2lgf5v7u0nou8c44v",
    "oauth": {}
};


export default awsmobile;
